# -*- coding: utf-8 -*-
"""Add_two_Numbers.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ENnda3_-dRpugWF69OrdKPUaTrmA9lcB
"""

def Cal():
  print("Welcome To Program")
  input1=input("Enter your first number")
  input1 = int(input1)
  input2=input("Enter your second number")
  input2 = int(input2)
  result= input1 + input2
  print(f"The sum of your numbers is = {result}")

Cal()